minecraft_version=26.1
minecraft_range=~26.1
java_version=25
loader_version=0.19.5
loom_plugin=net.fabricmc.fabric-loom
fabric_api_version=0.145.1+26.1
api_level=26.1
mixin_java=JAVA_25
gfx_family=ext
screen_family=26.1
core_family=26.1
